### ISSUE TITLE
Code block gets truncated when print the page as PDF

### ISSUE THREAD

**Issue by duongpc** [quasarframework/quasar-ui-qmarkdown#100]
**Describe the bug**
For a code block that spans into multiple pages, only the code in the first page is printed/the rest is truncated

**To Reproduce**
1. Make a really long code block
2. Ctrl + P and print as pdf
3. Only the first 60 lines (for example) are included in the pdf

**Expected behavior**
All lines are included in the pdf

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hawkeye64** [comment]
@duongpc No idea why this is happening. Any clues or suggestions? In the end, it's just divs, so should not have a problem.
Btw, which OS, what printer?

**Comment by duongpc** [comment]
@hawkeye64  I'm using Windows 10
`Microsoft Print to PDF` "printer"

**Comment by hawkeye64** [comment]
@duongpc More info has come to light. Please read this: https://forum.quasar-framework.org/topic/6867/printing-issues/2 and follow the link provided there.
