### ISSUE TITLE
Accessing an anchor leads to a slightly wrong place

### ISSUE THREAD

**Issue by wsw70** [quasarframework/quasar-ui-qmarkdown#103]
Link to the app code: https://gitlab.com/WoJ/testmarkdown2

**Describe the bug**

Accessing an anchor leads to a slightly wrong place

**To Reproduce**

After building the app, click on the PAGE ONE tab, and then choose one of the last entries on the right

**Expected behavior**

Going to an anchor, I expect to see that anchor on the page, but it is slightly above - I need to scroll up to see it

**Screenshots**

![image](https://user-images.githubusercontent.com/1345886/88335115-0f2f3680-cd33-11ea-90a3-224530b0b5ae.png)

![image](https://user-images.githubusercontent.com/1345886/88335206-3423a980-cd33-11ea-8e92-51410cb17b67.png)

![image](https://user-images.githubusercontent.com/1345886/88335281-574e5900-cd33-11ea-8f71-ccbe1e94fee9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 84

**Comment by hawkeye64** [comment]
This is the browser doing it. It will move anchor to top of screen, regardless if you have a banner showing (in which case it will be underneath and not visible).

In this case, you need to control the scrolling. I have this same similar code in all of my examples for this: https://github.com/quasarframework/quasar-ui-qcalendar/blob/dev/demo/src/layouts/Examples.vue#L245-L289

Also, notice the "onScroll" here: https://github.com/quasarframework/quasar-ui-qcalendar/blob/dev/demo/src/layouts/Examples.vue#L2
