### ISSUE TITLE
feat: Have option to replace <a href="..."> with Vue Router links

### ISSUE THREAD

**Issue by 34fame** [quasarframework/quasar-ui-qmarkdown#107]
**Is your feature request related to a problem? Please describe.**
Internal links are recognized by QMarkdown but browser is handling the redirect which is causing full page loads.

**Describe the solution you'd like**
Either replace links dynamically or provide a markdown link syntax to tell QMarkdown this is a Vue Router link

**Describe alternatives you've considered**
None other than the described solution but @hawkeye64 knows best!

**Additional context**
Thanks for all you do!! 👍🏻

**Comment by hawkeye64** [comment]
After consideration, this cannot be done. The markdown is not processed by Vue compiler, so can't have anything other than HTML.

I will leave this open for a while in case anyone can think of a way this can be done.

**Comment by hawkeye64** [comment]
@34fame Sorry Troy, could not come up with a good way of doing this.
