### ISSUE TITLE
Allow default options

### ISSUE THREAD

**Issue by tamirvs** [quasarframework/quasar-ui-qmarkdown#114]
If, for example, I want to disable Linkify in all my markdown pages I have to specifically add ```no-linkify``` to each page. It would be nice to have an option for default behavior across the app instead of repeating the same code in each page.  
I'm not sure how to implement it though, otherwise I'd offer a PR

**Comment by hawkeye64** [comment]
@tamirvs This is an idea that warrants a discussion on the best way to handle this so that all platforms can use it.

**Comment by Grawl** [comment]
I want to apply `no-heading-anchor-links` on all `q-markdown` elements

**Comment by hawkeye64** [comment]
@Grawl Do you have a suggestion on a global configuration? Possibly adding it to the Vue instance, maybe?

**Comment by Grawl** [comment]
Yes

**Comment by hawkeye64** [comment]
This was added in this release: https://github.com/quasarframework/quasar-ui-qmarkdown/releases/tag/v2.0.0-alpha.7
Sorry, I forgot to mention it.
