### ISSUE TITLE
add rel="noopener noreferrer" for external links & phishing

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar-ui-qmarkdown#138]
Wondered if you would consider setting external links parsed by linkify to get the attribute:

`rel="noopener noreferrer"`

by default based on this:

https://gosink.in/are-you-making-website-vulnerable-target-blank-or-performance/

**Comment by hawkeye64** [comment]
@smakinson Sounds like a good idea. Nothing I can do about it for a while as I am in deep on other projects atm.
Thanks for letting know about this though :heart:

**Comment by hawkeye64** [comment]
Added in v1.2.0 - thanks for the suggestion
