### ISSUE TITLE
IE syntax error

### ISSUE THREAD

**Issue by smakinson** [quasarframework/quasar-ui-qmarkdown#141]
Is this extension meant to be IE 11 compatible? (sorry!  :) )

I see a syntax error in the IE console and if I click to it and scroll up from it It looks like its under the sections for:

/*!
 * @quasar/quasar-ui-qmarkdown v1.0.35
 * (c) 2020 Jeff Galbraith <jeff@quasar.dev>
 * Released under the MIT License.
 */

A couple screenshots:

![Screen Shot 2020-11-12 at 9 56 29 AM](https://user-images.githubusercontent.com/16784/98956291-d5469380-24cd-11eb-8e76-a610350d5c6c.png)

and if you can see it, the cursor is in the Math. area in this one when I click on the error in the console:

![Screen Shot 2020-11-12 at 9 59 41 AM](https://user-images.githubusercontent.com/16784/98956392-f8714300-24cd-11eb-8c28-780061a8fc51.png)

**Comment by hawkeye64** [comment]
That looks like the embedded part of mardown-it, so I guess if they have IE11 issues, then QMarkdown will inherit that.

Yep, just tested and the docs site does not show up with IE11 :(
I don't have any plans to support IE11.

In fact. Micirisft is going to start redirecting IE11 to Edge in the coming year: https://docs.microsoft.com/en-us/deployedge/edge-learnmore-neededge

**Comment by smakinson** [comment]
@hawkeye64 Ok, thanks for checking on that and I like that coming redirect from MS, I will share that with the team.
