### ISSUE TITLE
q-markdown content is not reactive

### ISSUE THREAD

**Issue by vandelpavel** [quasarframework/quasar-ui-qmarkdown#157]
**Is your feature request related to a problem? Please describe.**
I was trying to add some mark down to my website when i noticed that the content is not reactive.

**Describe the solution you'd like**
Having a reactive content would be really usefull especially in cases like mine where the content should change based on language.

**Additional context**
```js
<q-markdown>
{{ $t(page.content )}}
</q-markdown>
```

**Comment by vandelpavel** [comment]
I solved it by simply pass the content through the `src` property like so:

```js
<q-markdown :src="$t(page.content" />
```

**Comment by hawkeye64** [comment]
@vandelpavel yes, this is an issue with Vue and slots unfortunately
