### ISSUE TITLE
Extension(@quasar/qmarkdown): is not compatible with quasar v2.0.0-beta.11. Required version: ^1.5.0

### ISSUE THREAD

**Issue by whiteua** [quasarframework/quasar-ui-qmarkdown#178]
Hello! 
I can't install @quasar/qmarkdown. I get the error "Extension(@quasar/qmarkdown): is not compatible with quasar v2.0.0-beta.11. Required version: ^1.5.0" by following these steps:
_Desctop:  Win 10_ 

run **quasar ext add @quasar/qmarkdown**

>  App · Installing "@quasar/qmarkdown" Quasar App Extension
> 
>  App · Retrieving "@quasar/quasar-app-extension-qmarkdown"...
>  App · [sync] Running "npm install --save-dev @quasar/quasar-app-extension-qmarkdown"
> 
> + @quasar/quasar-app-extension-qmarkdown@1.4.1
> added 37 packages from 46 contributors and audited 1729 packages in 14.585s

run **quasar upgrade**

>   Quasar CLI · Gathering information with npm...
>   Congrats! All Quasar packages are up to date.
> 

run **quasar dev**

>  Dev mode.......... spa
>  Pkg quasar........ v2.0.0-beta.11
>  Pkg @quasar/app... v3.0.0-beta.10
>  Debugging......... enabled       
> 
>  Configured browser support (at least 87.90% of global marketshare):
>  · Chrome for Android >= 89
>  · Firefox for Android >= 86
>  · Android >= 89
>  · Chrome >= 79
>  · Edge >= 86
>  · Firefox >= 77
>  · iOS >= 10.3
>  · Opera >= 69
>  · Safari >= 11
> 
>  App · Running "@quasar/qmarkdown" Quasar App Extension...
>  App · ⚠️  Extension(@quasar/qmarkdown): is not compatible with quasar v2.0.0-beta.11. Required version: ^1.5.0
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1        
> npm ERR! apps-com-amzroot@0.0.1 dev: `quasar dev`
> npm ERR! Exit status 1

**Comment by hawkeye64** [comment]
@whiteua QMarkdown has not been updated to be compliant with Quasar v2. In fact, QMarkdown breaks with Vue 3 (some functionality was **removed** that allows QMarkdown work in-line). You can follow this (Vue issue)[https://github.com/vuejs/vue-next/pull/1600] which is slated to be put into Vue 3.1

**Comment by whiteua** [comment]
Thank you for your reply.
