### ISSUE TITLE
QMarkdown support for Quasar V2

### ISSUE THREAD

**Issue by chowerth** [quasarframework/quasar-ui-qmarkdown#181]
Hello,

Just wondering when/if QMarkdown will support Quasar V2? Thanks.

Currently getting this versioning error: Extension(@quasar/qmarkdown): is not compatible with quasar v2.0.0-beta.9. Required version: ^1.5.0

![image](https://user-images.githubusercontent.com/56286587/113472602-66dd8000-9432-11eb-9136-f71151b279a8.png)

**Comment by chowerth** [comment]
I managed to find a [discord thread](https://discord.com/channels/415874313728688138/551066279943995397/811622420364132352) discussing the potential future of the extension. It seems it might be unsupported due to incompatibilities in Vue3.

**Comment by hawkeye64** [comment]
https://github.com/quasarframework/quasar-ui-qmarkdown/issues/178
