### ISSUE TITLE
IE11 - error blocks the whole app to load

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/quasar-ui-qmarkdown#213]
if you try to open a page of markdown-it in IE11 it doesn't show the markdown result but page is loaded. Which is OK, because you can inform a user about IE11 incompatibility.

**Describe the bug**
If the qmarkdown extension is added to the existing project or just opened the online demo it crash the IE11 from the beginning, so there is no way to inform user that it wouldn't work properly.

**To Reproduce**
1. Go to [qmarkdown demo](https://quasarframework.github.io/quasar-ui-qmarkdown/examples)
2. Open IE11 dev tools.
3. Error SCRIPT1002 wrong syntax
![image](https://user-images.githubusercontent.com/37825539/120706006-d4507000-c4b8-11eb-9ec9-a2fff1a398a9.png)

1. Go to [markdownit](https://markdown-it.github.io/)
2. Open IE11 dev tools
3. Error SCRIPT10002 but page is loaded
![image](https://user-images.githubusercontent.com/37825539/120706071-f0541180-c4b8-11eb-9714-eb3cfcf46314.png)

**Expected behavior**
Would be there a way to avoid crashing IE11 completely?

**Comment by hawkeye64** [comment]
@m0jimo That's news to me. Could have happened with the last markdown-it update. Any ideas what or where in the code is causing the issue?

**Comment by m0jimo** [comment]
It might be related to not polyfilled functions. It rise errors about webpack. There are some [examples](https://stackoverflow.com/questions/52982625/webpack-build-fails-for-ie-11) but i can try to investigate it after weekend.

**Comment by m0jimo** [comment]
@hawkeye64 the first investigation when trying to run a dev version locally is pretty simple. There is a missing IE11 in the Browser List. 
[ui/dev/package](https://github.com/quasarframework/quasar-ui-qmarkdown/blob/dev/ui/dev/package.json).
```json
"last 1 version, not dead, ie >= 11"
```
Demo `ui/demo` has been working locally in IE11 but not on [website](https://quasarframework.github.io/quasar-ui-qmarkdown/docs). So, the .json change above doesn't have a influence on it.

After building an extension I don't see any difference in dist folder files (except extra file `src/components/QMarkdown.json` - but it has no effect for extension).

**Comment by m0jimo** [comment]
Here are more detail from IE11.
![image](https://user-images.githubusercontent.com/37825539/121027275-1faf9a80-c7a7-11eb-8d32-5ea6301f5d95.png)

**Comment by hawkeye64** [comment]
On the live docs, it appears to be an issue with the Mermaid plugin (which isn't part of QMarkdown, but is used as an example of how to add a markdown-it plugin into QMarkdown)

![image](https://user-images.githubusercontent.com/10262924/121044551-caf22c80-c772-11eb-8be8-eef5f88829d1.png)

I'll investigate a bit more.

**Comment by hawkeye64** [comment]
Got it running on ie11
![image](https://user-images.githubusercontent.com/10262924/121049338-d8a8b180-c774-11eb-8694-b6a4643250bb.png)

This is not an issue with QMarkdown, but the site. It's because it's running as a JAMstack on github.io, some extra work had to be done to handle routes. In particular, it's this code:

```js
<!DOCTYPE html>
<html>
  <head>
    <title><%= productName %></title>

    <meta charset="utf-8">
    <meta name="description" content="<%= productDescription %>">
    <meta name="format-detection" content="telephone=no">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width<% if (ctx.mode.cordova || ctx.mode.capacitor) { %>, viewport-fit=cover<% } %>">

    <link rel="icon" type="image/png" sizes="128x128" href="icons/favicon-128x128.png">
    <link rel="icon" type="image/png" sizes="96x96" href="icons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="32x32" href="icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="icons/favicon-16x16.png">
    <link rel="icon" type="image/ico" href="favicon.ico">
  </head>
  <body>
    <script>
      (function(){
        let redirect = sessionStorage.redirect;
        delete sessionStorage.redirect;
        if (redirect && redirect !== location.href) {
          history.replaceState(null, null, redirect);
        }
      })();
    </script>

    <!-- DO NOT touch the following DIV -->
    <div id="q-app"></div>
  </body>
</html>
```
And, more specifically, this line:

```js
        let redirect = sessionStorage.redirect;
```

IE11 does not understand the `let` and that file doesn't run through webpack, so it not updated properly.
In this case, if you are building locally, you can change the `let` to `var`.

Because this does not really affect QMarkdown I am going to close this, but I won't be updating the site either to support IE11. On August 21, even if you start IE11, you will get Edge. There is support for IE11 for 1 more year from Microsoft, but that is only business accounts that have portals supporting 10000 or more employees. Officially, IE11 is dead. There is a lot of articles about it.

**Comment by m0jimo** [comment]
Thank for confirming that qmarkdown is IE11 compatible (I could see it on my own eyes after cloning and running it). It really helped me to track down issue in my app. 
Finally i discovered and fixed my app by removing <style> in one component as described in this [issue](https://github.com/JeffreyWay/laravel-mix/issues/2064).
