### ISSUE TITLE
It's not work under Quasar 2.0.1

### ISSUE THREAD

**Issue by willy-wonka-git** [quasarframework/quasar-ui-qmarkdown#232]
Hello! Will you release plugin for new version?

**Comment by jdfergason** [comment]
make sure you are using the `@next` version and it should work for you:

`quasar ext add @quasar/qmarkdown@next`

**Comment by hawkeye64** [comment]
@willy-wonka-git 

`quasar ext add @quasar/qmarkdown@next` to get the latest version that works for Quasar v2
