### ISSUE TITLE
Remove emoji plugin

### ISSUE THREAD

**Issue by Grawl** [quasarframework/quasar-ui-qmarkdown#255]
**Is your feature request related to a problem? Please describe.**
[markdown-it-emoji](https://github.com/markdown-it/markdown-it-emoji) is 15.76 KB gzipped size and I want to remove it from my bundle.

**Describe the solution you'd like**
In [src/components/QMarkdown.js](https://github.com/quasarframework/quasar-ui-qmarkdown/blob/ce8cef6c15f94eb729fc4627475b8cb100b4479f/ui/src/components/QMarkdown.js) file I can see following:

```js
import markdownIt from 'markdown-it'
import emoji from 'markdown-it-emoji'
import subscript from 'markdown-it-sub'
import superscript from 'markdown-it-sup'
import footnote from 'markdown-it-footnote'
import deflist from 'markdown-it-deflist'
import abbreviation from 'markdown-it-abbr'
import insert from 'markdown-it-ins'
import mark from 'markdown-it-mark'
// import container from 'markdown-it-container'
import taskLists from 'markdown-it-task-lists'
// import imsize from 'markdown-it-imsize'
import imsize from 'markdown-it-imsize/dist/markdown-it-imsize.js'
// import tocAndAnchor from 'markdown-it-toc-and-anchor'
```

So many plugins imported. I do not want them all in my bundle.

I suggest to allow customizing markdown-it plugins list.

For now, my boot file for `quasar-ui-qmarkdown` looks like this:

```js
import Plugin from '@quasar/quasar-ui-qmarkdown'
export default ({ Vue }) => {
	Vue.use(Plugin)
}
```

The good solution will be to allow custimizing plugins list in this file, like this:

```js
import Plugin from '@quasar/quasar-ui-qmarkdown'
export default ({ Vue }) => {
	Vue.use(Plugin, {
		plugins: [
			require('markdown-it-sub'),
			require('markdown-it-sup'),
			require('markdown-it-footnote'),
			require('markdown-it-deflist'),
			require('markdown-it-abbr'),
			require('markdown-it-ins'),
		],
	})
}
```

Something like [postcss-load-config](https://github.com/postcss/postcss-load-config).

**Describe alternatives you've considered**
I cannot find any alternative to remove module imported by third party dependency from my bundle.

**Comment by Grawl** [comment]
Yes, I am using Quasar v1 for now. 

quasar 1.15.23
@quasar/app 2.2.10
@quasar/quasar-app-extension-qmarkdown 1.4.3

**Comment by Grawl** [comment]
For now, I just replaced `q-markdown` with direct `markdown-it` usage

```vue
<script>
import MarkdownIt from 'markdown-it'

import markdownItAttributes from 'markdown-it-attrs'
import markdownItExternalLinks from 'markdown-it-external-links'

const md = new MarkdownIt({
	html: true,
	breaks: true,
	linkify: true,
})
md
	.use(markdownItAttributes)
	.use(markdownItExternalLinks, {
		externalTarget: '_blank',
		externalRel: 'noopener noreferrer',
		internalClassName: 'link',
	})

export default {
	props: {
		src: String,
	},
	computed: {
		render() {
			return md.render(this.src)
		},
	},
}
</script>
<template lang='pug'>
.markdown(v-html='render')
</template>
```

**Comment by hawkeye64** [comment]
@Grawl This is fixed in https://github.com/quasarframework/quasar-ui-qmarkdown/releases/tag/v2.0.0-alpha.7
Unfortunately, these changes will not be back ported into 1.x
