### ISSUE TITLE
Can't use markdown-it-mathjax3 plugin because of \n replacement from src attribute

### ISSUE THREAD

**Issue by profanat** [quasarframework/quasar-ui-qmarkdown#265]
**Describe the bug**
If you use markdown-it-mathjax3 plugin with q-markdown then you can't use any math expressions starting with \n like \notin because \n is getting replaced. Source code of the replacement https://github.com/quasarframework/quasar-ui-qmarkdown/blob/dev/ui/src/components/QMarkdown.js#L155

**To Reproduce**
1. Add markdown-it-mathjax3: 
    onExtend(mdi) {
      const mdMathJax = require("markdown-it-mathjax3");
      mdi.use(mdMathJax);
    },
2. Create q-markdown component:
``<q-markdown :extend="onExtend" :src="`
$$A \\setminus B = \\{ x\\mid x\\in A \\text{ and } x \\notin B\\}.$$
`"></q-markdown>``

**Expected behavior**
![image](https://user-images.githubusercontent.com/1935988/132104658-84b24356-7b8f-495b-b9af-bcaa089ce716.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/1935988/132104681-2ae1a1fd-8e55-40e4-b85c-c8dac46735e7.png)

**Suggested solution**
Add property to NOT do the \n replacement

**Comment by hawkeye64** [comment]
Fixed in QMarkdown v2.0.0-alpha.6.
If you need this for v1.x let me know.
