### ISSUE TITLE
Support for v2

### ISSUE THREAD

**Issue by gorango** [quasarframework/quasar-ui-qmarkdown#344]
**Is your feature request related to a problem? Please describe.**

`Extension(@quasar/qmarkdown): is not compatible with quasar v2.2.3. Required version: ^1.5.0`

**Describe the solution you'd like**

Add support for Quasar v2 with Vue3 and Typescript.

**Describe alternatives you've considered**

N/A

**Comment by hawkeye64** [comment]
Install with:
```
quasar ext add @quasar/qmarkdown@next
```

**Comment by chrislandeza** [comment]
@hawkeye64 is v2 working? Tried installing it via `quasar ext add @quasar/qmarkdown@next
`but the markdown is not rendering properly.

![image](https://user-images.githubusercontent.com/4858242/148729575-58361b93-8a58-49d4-95df-f73bd198d72e.png)

![image](https://user-images.githubusercontent.com/4858242/148729609-7f56219a-66fc-4c25-ae0a-bca01bec17e4.png)


I'm getting the same issue on the live documentation https://qmarkdown.netlify.app/examples/containers
![image](https://user-images.githubusercontent.com/4858242/148729674-9bdfe9a5-8bc7-4066-9ff3-44237ffdef67.png)

**Comment by hawkeye64** [comment]
I fixed the examples. The indentation was off.

Speaking of which, indentation is very important in markdown processing. Having it indented the same as your HTML won't work.
Keep it left-justified.
