### ISSUE TITLE
Provide a way to add additional code-highlighters for Prism

### ISSUE THREAD

**Issue by michael-hillmann** [quasarframework/quasar-ui-qmarkdown#36]
When writing the language selector for C++, which is listed in prism.js documents (cpp), there is no syntax highlightning at all.

**Comment by hawkeye64** [comment]
You're right. That's not one of the default languages.
![image](https://user-images.githubusercontent.com/10262924/66277704-80166800-e85f-11e9-90a0-348af73f56d8.png)
You can try `clike` and see if that gives you what you want.
In the meantime, I will change issue title to something a bit more appealing :)

**Comment by mesqueeb** [comment]
I'd love to be able to use other Prism theme's like the COY theme:
<img width="823" alt="image" src="https://user-images.githubusercontent.com/3253920/67135690-2fd3d880-f257-11e9-864e-29e67902b481.png">

**Comment by eladcandroid** [comment]
Need something similar for Dart.. Thanks!

**Comment by hawkeye64** [comment]
@eladcandroid I don't know what you mean.

**Comment by eladcandroid** [comment]
@hawkeye64 
https://dart.dev/

**Comment by hawkeye64** [comment]
@eladcandroid Forgive me, I still don't see the relevance with QMarkdown. What am I missing?

**Comment by eladcandroid** [comment]
@hawkeye64 
You right that prism is just another library but you assume in your code that we need to highlight only html/vue code:

https://github.com/quasarframework/app-extension-qmarkdown/blob/29623d9a9eebe0c7e022d575102db9e735061055/src/markdown.js#L33

https://github.com/quasarframework/app-extension-qmarkdown/blob/b7afb1d3fbfb7f8be70c3f4ec7040000118d7eb0/src/lib/highlight.js#L4

**Comment by hawkeye64** [comment]
@eladcandroid Actually, it uses the prism defaults which are highlighted in my first message to this thread. Don't worry, you'll soon be able to add highlight languages like rust, dart, flutter, or whatever else you want, as long as you provide the proper highlighting code.

**Comment by hawkeye64** [comment]
This has been added with the new `extend-prism` property in v1.0.0 - enjoy
