### ISSUE TITLE
Can't compile with @quasar/app-webpack v3.4.0

### ISSUE THREAD

**Issue by GeekyMonkey** [quasarframework/quasar-ui-qmarkdown#363]
Using quasar upgrade cli, upgraded existing Quasar 2.5.5 app to Quasar 2.6.0
@quasar/app from 3.3.3 to @quasar/app-webpack v3.4.0

"@quasar/quasar-app-extension-qmarkdown": "2.0.0-beta.2",

Now getting an error when trying to start the dev server: 

Extension(@quasar/qmarkdown): Extending quasar.config.js...
C:\SourceCode\SafeTrx\atlas-davra\packages\active\ui\node_modules\@quasar\quasar-app-extension-qmarkdown\src\index.js:23
  const oldPreTagFunc = conf.build.vueLoaderOptions.compilerOptions.isPreTag
                                                                    ^

[  TypeError: Cannot read properties of undefined (reading 'isPreTag')

**Comment by xLuckySzx** [comment]
I had the same issue, and was able to solve it by:

Installing @quasar/app-webpack 3.4.0
Replacing every occurrency of '@quasar/app' to '@quasar/app-webpack'
And fixing '@quasar/app' imports

You might also need to manually 

npm i --save vue 
npm i --save vue-router

after updates

**Comment by hawkeye64** [comment]
Yes, I am working on it this weekend.

**Comment by hawkeye64** [comment]
Fixed in v2.0.0-beta.3/4 (released today)

**Comment by hawkeye64** [comment]
```
quasar upgrade -i
```
To automatically upgrade

**Comment by GeekyMonkey** [comment]
Thank you hawkeye64!  Confirmed fix worked.
