### ISSUE TITLE
Cannot render emojis in next version

### ISSUE THREAD

**Issue by baka-gourd** [quasarframework/quasar-ui-qmarkdown#366]
For a legitimate bug, in order to process faster, please go here https://codesandbox.io/s/qcalendar-bx1y7, fork the codesandbox, add code to reproduce the bug and submit link here:

**Describe the bug**
https://codepen.io/baka-gourd/pen/OJzarwX

**Expected behavior**
Render emoji and others.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser edge 100

**Comment by baka-gourd** [comment]
sorry for i forget import plugin

**Comment by hawkeye64** [comment]
In order to make QMarkdown less heavy, some of the markdown-it plugins were removed. But, a means was added for developers to put them back on an as needed basis: https://qmarkdown.netlify.app/developing/using-qmarkdown#Extending-with-Plugins
