### ISSUE TITLE
Qmarkdown is not compatible with quasar v2.6.6. Required version: ^1.5.0

### ISSUE THREAD

**Issue by aapnetin** [quasarframework/quasar-ui-qmarkdown#368]
When i use the command `quasar describe QMarkdown  ` am getting following message :

Extension(@quasar/qmarkdown): is not compatible with quasar v2.6.6. Required version: ^1.5.0

Am i missing something ?

**Comment by hawkeye64** [comment]
You've upgraded quasar, but haven't updated to the version of QMarkdown that supports Quasar v2
Here are the docs: https://qmarkdown.netlify.app/

**Comment by aapnetin** [comment]
Installed QMarkdown using Quasar CLI command : `quasar ext add @quasar/qmarkdown` 
Tried upgrading it with  `quasar upgrade -i` not working.

Removing QMarkdown with `quasar ext remove @quasar/qmarkdown` and re adding it using command `quasar ext add @quasar/qmarkdown@next` as mentioned in new QMarkdown documentation works !

Thanks to @hawkeye64 for pointing me in right direction.

**Comment by JackChanel** [comment]
> 使用 Quasar CLI 命令安装了 QMarkdown：`quasar ext add @quasar/qmarkdown` 尝试升级它，但 `quasar upgrade -i`没有起作用。
> 
> 按照新 QMarkdown 文档中提到的方法使用命令删除 QMarkdown`quasar ext remove @quasar/qmarkdown`并重新添加它！`quasar ext add @quasar/qmarkdown@next`
> 
> 由于@hawkeye64为我指明正确的方向。

Thanks for all of helps~
