### ISSUE TITLE
Can't import md files after upgrade from 2.0.0-beta.2 to 2.0.0-beta.7

### ISSUE THREAD

**Issue by Dirk-** [quasarframework/quasar-ui-qmarkdown#369]
I upgraded qmarkdown from 2.0.0-beta.2 → 2.0.0-beta.7. Now all my md files produce an error like this if I run `quasar dev`:

```
 App •  ERROR  •  UI  in ./src/markdown/hilfe.md

Module parse failed: Unexpected character ' ' (1:1)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

```

The unexpected character is either a blank space or a hash. The md files live in my `src` folder and I import them like `import hilfe from '../markdown/hilfe.md'` (vue file is in `src/pages`).

I read in the commit notes from March 19th that there is a breaking change: `breaking(app-ext): Support for importing md and vmd files no longer supported.` Is this the problem? The docs still say I can import md files and I really need that. Do I have to move them into the assets folder?

**Comment by hawkeye64** [comment]
Here is the release that re-instated *.md imports: https://github.com/quasarframework/quasar-ui-qmarkdown/releases
Read the notes. You may have to do an invoke. Report back and let me know if that solved it for you.

**Comment by Dirk-** [comment]
> Here is the release that re-instated *.md imports: https://github.com/quasarframework/quasar-ui-qmarkdown/releases
> Read the notes. You may have to do an invoke. Report back and let me know if that solved it for you.

This solved it indeed. Thank you very much!
