### ISSUE TITLE
How to get rid of bullet points?

### ISSUE THREAD

**Issue by MarisKay** [quasarframework/quasar-ui-qmarkdown#371]
Hello, i was not able to find a way how to disallow all kinds of bullet points etc. I am looking for a way to get pure paragraphs with linkify enabled. Nothing more. But it turns out there's lots of goodies that sneak out one or another way when user enters some kind of character combination or like in bullet example simple minuses with an offset and line of text. Even Demo does not show any way to remove bullet points. Pls advise! Thank you!

**Comment by hawkeye64** [comment]
I am not entirely sure what you mean. If you start a line with a dash, it will be turned into a bullet point. That is basic markdown from the spec. Am I misunderstanding what it is that you want to accomplish?

**Comment by MarisKay** [comment]
Hey there, thanks for taking time to answer. What I mean is that i would love to have more control over which elements of markdown to allow and which dont. For example right now in my case i would be super glad to use only linkify, paragraphs and nothing else. In other project the set of allowed elements could be different. Depending on what project needs. Right now there is no way i can have ANY control over this :/

**Comment by MarisKay** [comment]
Hey there, any progress towards this customization? Thanks

**Comment by nucle** [comment]
Hi,

did u try the properties?

![image](https://user-images.githubusercontent.com/2041897/196004754-1b08a2b9-ab02-45bc-b2a4-d55929a7b868.png)


When something is missing could add it.

BR,
nucle

**Comment by MarisKay** [comment]
Hey Nucle, thanks for chiming in! Yes, i played with the properties. In my case i was not able to fully achieve pure text + linkifying detected urls. Somehow always something sneaks in when user adds content to my site that ruins the clean look. 

How would you set the properties to allow only :

1) Pure unformated text with linebreaks.
2) All URLs automatically converted to clickable links.
3) nothing else, no H tags, no text sizes, bolds, styles etc.. nothing.

Also, about links - would be great to have an option to display only domain name instead of having the whole long link presented to the user with all the url parameters like ?something=0293r034&blabla=510923 etc. The end user doesn't have to know all the parameters etc., that's a tech stuff, not usable when you read a post in my case. That makes it unreadable and is not helping in any way. At the same time - it is better than simply placing a word LINK.. since end user has to know at least to what site the link is going.

Please advise, 
Thank you!

**Comment by nucle** [comment]
Hi,
at the end of the day i can take a look.

BR

**Comment by nucle** [comment]
@MarisKay 

Do u mean when u edit the the markdown or when u see the parsed content?

**Parsed content** 

* Requirement: Plugin Linkify
*  You can override the plugin an change it  [Issue 374 with example](https://github.com/quasarframework/quasar-ui-qmarkdown/issues/374)

````js
[MyHomepage](https://github.com/quasarframework/quasar?something=0293r034&blabla=510923)
````
Will be displayed as:
![image](https://user-images.githubusercontent.com/2041897/197328750-01f89550-b764-4bbb-9468-e1f5332f15f8.png)

**Plain content**

- You could use slugs instead of such urls like `quasar/something-blabla`
- Use another plugin like https://github.com/martinheidegger/markdown-it-replace-link. Create placeholder and replace it on the fly
- Code your own plugin


BR,
nucle

**Comment by MarisKay** [comment]
@nucle 

yes, i know there's [myhomepage](https://....) syntax, but problem here is that my average regular user is a non tech person 60+ so expecting them to start using urls syntax like [myhomepage](https://...) would be way too optimistic scenario. At best they can copy paste full url.

And then there are those 5% of users who manage to sneak some html formating in, not sure how and what they write but at the end when i am outputting the content - in these cases formating jumps out of the whole context.

That's why i wondered whether it would be possible to add the customization so it would only allow linkifying and simple text with linebreaks, nothing more. As i understand, i can't achieve this config by twekaking current markdown's settings?

Coding my own solution and stuff like that is way too early for me so not even considering that as an option. I am in my first project right now with quasar js, so definitely not a pro here. Before i was doing purely php mysql.

Thanks

**Comment by hawkeye64** [comment]
> @nucle
> 
> yes, i know there's [myhomepage](https://....) syntax, but problem here is that my average regular user is a non tech person 60+ so expecting them to start using urls syntax like [myhomepage](https://...) would be way too optimistic scenario. At best they can copy paste full url.
> 
> And then there are those 5% of users who manage to sneak some html formating in, not sure how and what they write but at the end when i am outputting the content - in these cases formating jumps out of the whole context.
> 
> That's why i wondered whether it would be possible to add the customization so it would only allow linkifying and simple text with linebreaks, nothing more. As i understand, i can't achieve this config by twekaking current markdown's settings?
> 
> Coding my own solution and stuff like that is way too early for me so not even considering that as an option. I am in my first project right now with quasar js, so definitely not a pro here. Before i was doing purely php mysql.
> 
> Thanks

If your users are adding URLs, you can detect this from your input and automatically convert them on the fly.

As for the title of this issue with the bullet points, you can modify how they look through css.
