### ISSUE TITLE
Override font size

### ISSUE THREAD

**Issue by JacksonBowe** [quasarframework/quasar-ui-qmarkdown#377]
Inside QMarkdown.sass file there are a number of css settings that I would like to override. Unfortunately I can't because they are tagged with "!important".

eg:
```sass
&--heading

    &-h1
      font-size: 3rem !important
      line-height: 2rem !important
      padding: 1rem 0
      font-weight: 500
      margin: 0 0 1rem
```

As far as I can tell this makes it impossible to change the font size of header elements.

If there is a way I'm missing would be much appreciated. Cheers

**Comment by nucle** [comment]
Hi,
you can override the style I pasted an example.
In the next release I will check another solution.



```
.q-markdown--heading-h1 {
  color: orange;
  font-size: 6rem !important;
  line-height: 4rem !important
}
```

![image](https://user-images.githubusercontent.com/2041897/196004307-e49bb90e-3780-4f9d-abc5-0229c2d28e2d.png)


BR,
nucle
