### ISSUE TITLE
Does not seem to work on newer V2 Quasar versions?

### ISSUE THREAD

**Issue by burkongla** [quasarframework/quasar-ui-qmarkdown#380]
Hi,
I have tried to install the extension on 3 projects, the last two on new quasar projects whose repositories I have added here. There is no error, but it does not seem to do anything.

1. I first run "npm init quasar"
2. Vite / Webpack (issues on both)
3. quasar ext add @quasar/qmarkdown@next
4. At this point I don't see any particular changes in quasar.config.js, but tried anyway. Did not seem to work.
5. Add (or equivalent for webpack) `vueLoaderOptions: {
        compilerOptions: {
          isPreTag: (tag) => tag === 'pre ' || tag === 'q-markdown'
        }
      },`
6. Not really any error as far as I can see, but the markdown does not seem to work.

Here are the repositories of the fresh quasar projects I tested:
https://github.com/burkongla/qmarkdown-webpack-issues
https://github.com/burkongla/qmarkup-vite-issues

Here is an example of the IndexPage.vue which I attempted to use q-markdown in:
(Had some issues with posting it as a code block, here is link to IndexPage instead)
https://github.com/burkongla/qmarkup-vite-issues/blob/master/src/pages/IndexPage.vue

Expected behaviour:
Text to be displayed as in the samples provided here: 
https://qmarkdown.netlify.app/developing/using-qmarkdown#Code

Screenshot:
![image](https://user-images.githubusercontent.com/3776936/195961790-8b14f43f-b730-4668-a66a-3f680dee21ba.png)

**Comment by nucle** [comment]
Hi,
i cloned your repository and it works.
You should take care of your file indentations.

Maybe it is better when u use a file.


![image](https://user-images.githubusercontent.com/2041897/196004092-36bd121d-e813-41c4-9560-fbe3d3bbde1c.png)


![image](https://user-images.githubusercontent.com/2041897/196004044-27c11e1f-3924-4c00-bd89-3c23fad11fbe.png)


BR,
nucle

**Comment by burkongla** [comment]
Thank you for your time, I appreciate it! This was also the issue on the main project also. I must have not realized that it was linting those lines on save and that it would cause the issue.
