### ISSUE TITLE
Links from markdown files aren't capturing the route of the page

### ISSUE THREAD

**Issue by mepearson** [quasarframework/quasar-ui-qmarkdown#383]
The markdown code is generating links on the headers, but it is appending the #<title> to the root of the app and not to the current page.

I.e. if the site is located at **localhost:9000/#/** and you click a markdown link on the page **localhost:9000/#/about** documentation the resulting link is: `localhost:9000/#<title anchor>` rather than `localhost:9000/#/about#<title anchor>`

Tried to recreate this on the linked sandbox but getting a sandbox error when I open the calendar app. 

Assume this is an issue in the vue routing, but am new to Vue so haven't figured out how to tap into it properly

**Comment by Jille** [comment]
Are you using Server Side Rendering?

**Comment by hawkeye64** [comment]
You can't use header or hash links in pages with vue-router mode of "hash", you can only use "history".
