### ISSUE TITLE
Extra line breaks

### ISSUE THREAD

**Issue by Daemach** [quasarframework/quasar-ui-qmarkdown#385]
I'm using this in a UMD application.  The only change I made was wrapping a mustache with <q-markdown> as below, but the table is no longer dense because it's wrapping the values with paragraph tags.  The markdown itself seems to be working.
```
<span v-if="props.row.type == 'info' || props.row.type == 'done'" > <q-markdown>{{props.row.message}}</q-markdown> </span>
```

![image](https://github.com/quasarframework/quasar-ui-qmarkdown/assets/12553953/a257409a-3aeb-4503-9562-39ddf85425ed)

![image](https://github.com/quasarframework/quasar-ui-qmarkdown/assets/12553953/88bbb573-27de-488a-a8a2-d36b339db42f)

**Comment by nucle** [comment]
Hi,
try to override the style of your p tag.
BR

**Comment by hawkeye64** [comment]
Yes, in this instance, you will need to override the behaviour of the <p> tag so it has no margin on the bottom.
