### ISSUE TITLE
Add a line how to install this extension

### ISSUE THREAD

**Issue by hipertracker** [quasarframework/quasar-ui-qmarkdown#392]
Why is there not a single line in README about the installation????

**Comment by hawkeye64** [comment]
It depends on how you want to install it. From the main README, click on either `ui` for stand-alone installation or `app-extension` if you plan on installing it that way (more automated).

![image](https://github.com/user-attachments/assets/9ac23e0d-5322-4a8d-9edf-b51c6c7992a1)
