### ISSUE TITLE
IDE IntelliJ `Unknown html tag q-markdown `

### ISSUE THREAD

**Issue by MartinX3** [quasarframework/quasar-ui-qmarkdown#394]
It works but my IDE IntelliJ reports `Unknown html tag q-markdown` and I don't have any autocompletion.

**Comment by MartinX3** [comment]
ping @hawkeye64

**Comment by hawkeye64** [comment]
I don't know IntelliJ, but you can find type information in the dist/types folder if that helps. That seems to work with vs-code and it finds it automatically.
