### ISSUE TITLE
SASS Deprecation Warnings

### ISSUE THREAD

**Issue by zanzara** [quasarframework/quasar-ui-qmarkdown#399]
With latest Quasar 2.17.0 and app-vite-v2.0.0-beta.22  
there are a lot of SASS Deprecation Warnings arising running cmd: `quasar dev | build` 

```
   color: lighten($blue-8, 10%)
    │                ^^^^^^^^^^^^^^^^^^^^^
    ╵
    ../../../@quasar/quasar-ui-qmarkdown/src/components/QMarkdown.sass 171:16  @import
    ../../../@quasar/quasar-ui-qmarkdown/src/index.sass 3:9                    root stylesheet

Deprecation Warning: lighten() is deprecated. Suggestions:

color.scale($color, $lightness: 18.5454545455%)
color.adjust($color, $lightness: 10%)

More info: https://sass-lang.com/d/color-functions
```

**To Reproduce**
1. Create a new Quasar CLi project with latest Qusar 2.17.0 and latest app-vite-beta-22
2. Include this AE qmarkdown
3. Start `quasar dev`  or `qusar build` 

**Expected behavior**
No SASS warnings.

**Remedies**
Replace depracted  SASS `lighten`  with SASS  proposals above.

**Comment by rstoenescu** [comment]
q/app-vite beta.23 suppresses deprecation warnings like this one, so upgrading to it will make the markdown AE work.

**Comment by zanzara** [comment]
@rstoenescu  Thx, for making a new app-vite-beta-23  but unfortunately it didn't solved this warnings above:
Still got this messages:
```
Debugger listening on ws://127.0.0.1:5858/f5a0713b-7d77-450a-a036-758d7d46e7a9
For help, see: https://nodejs.org/en/docs/inspector
Warning: Future import deprecation is not yet active, so silencing it is unnecessary.

Warning: Future import deprecation is not yet active, so silencing it is unnecessary.

Warning: Future global-builtin deprecation is not yet active, so silencing it is unnecessary.

Warning: Future global-builtin deprecation is not yet active, so silencing it is unnecessary.

Warning: Future import deprecation is not yet active, so silencing it is unnecessary.

Warning: Future global-builtin deprecation is not yet active, so silencing it is unnecessary.

Deprecation Warning: lighten() is deprecated. Suggestions:

color.scale($color, $lightness: 48.417721519%)
color.adjust($color, $lightness: 30%)

More info: https://sass-lang.com/d/color-functions

    ╷
160 │       border-left: 10px solid lighten($grey-8, 30%)
    │                               ^^^^^^^^^^^^^^^^^^^^^
    ╵
    ../../../@quasar/quasar-ui-qmarkdown/src/components/QMarkdown.sass 160:31  @import
    ../../../@quasar/quasar-ui-qmarkdown/src/index.sass 3:9                    root stylesheet

Deprecation Warning: lighten() is deprecated. Suggestions:

color.scale($color, $lightness: 16.1392405063%)
color.adjust($color, $lightness: 10%)

More info: https://sass-lang.com/d/color-functions

    ╷
163 │         color: lighten($grey-8, 10%)
    │                ^^^^^^^^^^^^^^^^^^^^^
    ╵
    ../../../@quasar/quasar-ui-qmarkdown/src/components/QMarkdown.sass 163:16  @import
    ../../../@quasar/quasar-ui-qmarkdown/src/index.sass 3:9                    root stylesheet

Deprecation Warning: lighten() is deprecated. Suggestions:

color.scale($color, $lightness: 55.6363636364%)
color.adjust($color, $lightness: 30%)

More info: https://sass-lang.com/d/color-functions

``` 
and so on.
Should i clear sm cache before?

**Comment by zanzara** [comment]
went back again for `app-vite-beta.22` for the moment

**Comment by PauloFerreira25** [comment]
From what I understand, it would have to do with the sass version

https://classic.yarnpkg.com/en/package/sass#changelog

**Comment by zanzara** [comment]
@PauloFerreira25  maybe.  I got Sass  1.79.3   in node_modules. Latest is 1.80.2

How should I update Sass to latest?

` yarn upgrade sass --dev --latest`  doesn't work. Got lock-file error then.

and adding this to `package.json`aswell didn't help.
```json
  "resolutions": {
    "sass": "1.80.2"
  }
``` 
any ideas?

**Comment by zanzara** [comment]
got it! It's `sass-embedded`  not  `sass`
```json
  "resolutions": {
    "sass-embedded": "1.80.2"
  }
  ```
  @rstoenescu  now it works w/o warnings w/  `app-vite-beta-23` 
  Should be mentioned smw, pls.

**Comment by rstoenescu** [comment]
You don't need that. Just do a clean install

**Comment by zanzara** [comment]
> You don't need that. Just do a clean install

You mean with `clean install` delete `node_modules`  and lock file  and do a `yarn install` afterwards?

**Comment by zanzara** [comment]
my summary:  even updating to latest  app-vite-beta.23 and sass-embedded 1.80.2  did not help to mitigate the origin Sass warnings from this AE markdown.
I still need to use the `silenceDeprecations: ['color-functions']`   in  `viteConf.css`

**Comment by rstoenescu** [comment]
Yes, you may need to further add stuff to the silenceDeprecations array. But if you do, make sure that you are pushing to that array in your extendVite() rather than overriding it completely.

**Comment by zanzara** [comment]
> Yes, you may need to further add stuff to the silenceDeprecations array. But if you do, make sure that you are pushing to that array in your extendVite() rather than overriding it completely.

Yes, I think I did it as you propose. That's in my `quasar.conf.js`
```js
    extendViteConf (viteConf) {
        viteConf.css = mergeConfig(viteConf.css, {
          preprocessorOptions: {
            // silence deprecation warnings from quasar-ui-qmarkdown
            sass: {
              silenceDeprecations: ['color-functions']
            },
            scss: {
              silenceDeprecations: ['color-functions']
            }
          }
        })
```

**Comment by sonicviz** [comment]
I upgraded my quasar webpack app and now getting these same warnings. 
How can I resolve them?

**Comment by rstoenescu** [comment]
@hawkeye64 can u switch to `@use "sass:colors"` pls? https://sass-lang.com/documentation/breaking-changes/color-functions/

**Comment by sonicviz** [comment]
Related issue with webpack here https://github.com/quasarframework/quasar-ui-qmarkdown/issues/400#issue-2635967896 as Vite solutions suggested don't seem to work for webpack.

**Comment by hawkeye64** [comment]
This should be fixed with the v2 release. If not, you can reopen this ticket.

**Comment by sonicviz** [comment]
Awesome, ty.

**Comment by sonicviz** [comment]
Related, error in webpack. 
https://github.com/quasarframework/quasar-ui-qmarkdown/issues/401#issuecomment-2552655517
