### ISSUE TITLE
SASS Deprecation Warnings w/ quasar/app-webpack": "^3.14.2",

### ISSUE THREAD

**Issue by sonicviz** [quasarframework/quasar-ui-qmarkdown#400]
**Describe the bug**

I upgraded my quasar webpack app and now getting these warnings below.
How can I resolve them with webpack?

ref: https://sass-lang.com/documentation/breaking-changes/color-functions/

Deleting node-modules and importing again they still show running Quasar Dev.
Using "@quasar/app-webpack": "^3.14.2",

****Copy/Paste
App • WARNING • UI in ./node_modules/@quasar/quasar-ui-qmarkdown/src/index.sass

Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Warning on line 159, column 30 of file:///E:/Source%20Control/AI%20Apps/My%20Quasar%20Apps/Quapp/quapp2/node_modules/@quasar/quasar-ui-qmarkdown/src/components/QMarkdown.sass:159:30:
lighten() is deprecated. Suggestions:

color.scale($color, $lightness: 48.417721519%)
color.adjust($color, $lightness: 30%)

More info: https://sass-lang.com/d/color-functions

159 | border-left: 10px solid lighten($grey-8, 30%)

......https://github.com/quasar\quasar-ui-qmarkdown\src\components\QMarkdown.sass 160:31 https://github.com/import
......https://github.com/quasar\quasar-ui-qmarkdown\src\index.sass 1:9 root stylesheet

......https://github.com/quasar\quasar-ui-qmarkdown\src\components\QMarkdown.sass 171:16 https://github.com/import
......https://github.com/quasar\quasar-ui-qmarkdown\src\index.sass 1:9 root stylesheet

**Comment by hawkeye64** [comment]
This should be fixed with the v2 release. If not, you can reopen this ticket.
