### ISSUE TITLE
Does not work with quasar/app-webpack v4 (beta)

### ISSUE THREAD

**Issue by sonicviz** [quasarframework/quasar-ui-qmarkdown#401]
**Describe the bug**

Create a new basic Quasar quickstart project as described here: https://quasar.dev/quasar-cli-webpack/upgrade-guide.
npm init quasar
When asked to "Pick Quasar App CLI variant", answer with: "Quasar App CLI with Webpack (BETA | next major version - v4)".

Adding quasar-ui-markdown via quasar ext add @quasar/qmarkdown@next

Results in the following error: 
 App • Installing "@quasar/qmarkdown" Quasar App Extension

 App • Installing @quasar/quasar-app-extension-qmarkdown@next...
 App • [sync] Running "npm install --save-dev @quasar/quasar-app-extension-qmarkdown@next" in E:\Source Control\AI Apps\My Quasar Apps\quasar-project

added 34 packages, and audited 952 packages in 9s

195 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
node:path:433
      validateString(arg, 'path');
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at join (node:path:433:7)
    at #getScriptFile (E:\Source Control\AI Apps\My Quasar Apps\quasar-project\node_modules\@quasar\app-webpack\lib\app-extension\AppExtensionInstance.js:346:22)
    at #getScript (E:\Source Control\AI Apps\My Quasar Apps\quasar-project\node_modules\@quasar\app-webpack\lib\app-extension\AppExtensionInstance.js:358:39)
    at #getScriptPrompts (E:\Source Control\AI Apps\My Quasar Apps\quasar-project\node_modules\@quasar\app-webpack\lib\app-extension\AppExtensionInstance.js:304:51)
    at AppExtensionInstance.install (E:\Source Control\AI Apps\My Quasar Apps\quasar-project\node_modules\@quasar\app-webpack\lib\app-extension\AppExtensionInstance.js:218:49)
    at async runExtAction (E:\Source Control\AI Apps\My Quasar Apps\quasar-project\node_modules\@quasar\app-webpack\lib\cmd\ext.js:69:3) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.12.2

This will then cause errors in md files when you try to run quasar dev 
eg: Module parse failed: Unexpected character ' ' (1:1)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> # News
|

**To Reproduce**
Create a new basic Quasar quickstart project as described here: https://quasar.dev/quasar-cli-webpack/upgrade-guide.
npm init quasar
When asked to "Pick Quasar App CLI variant", answer with: "Quasar App CLI with Webpack (BETA | next major version - v4)".
let it create the project
CD into the new project 
Run quasar ext add @quasar/qmarkdown@next and receive your new error

**Expected behavior**

Expect it to not error, and work correctly as it does in "@quasar/app-webpack": "^3.14.2",

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 11 X64 Pro 23H2 latest

**Additional context**

**Comment by hawkeye64** [comment]
This should be fixed with the v2 release. If not, you can reopen this ticket.

**Comment by sonicviz** [comment]
Thanks for the update. 
I'd converted over to vue-markdown-render, but reinstalled to test the update with webpackV4. 

Unfortunately, it gives me an error, as below. I
I'd take a stab at debugging it but not familiar with how to import the plugin source into my project in order to do that. 
Can you elaborate on how to do that, then I can take a shot at unpicking it. 
![image](https://github.com/user-attachments/assets/34a1f206-f57f-4064-ab75-91627f9e223e)

**Comment by sonicviz** [comment]
How do I reopen this? It's not fixed, it throws an error trying to run Quasar Dev. 
Happy to work on it with some debug guidance.

**Comment by sonicviz** [comment]
This doesn't work with Quasar Webpack V4+. 
The documentation is also now incorrect @ https://qmarkdown.netlify.app/developing/using-qmarkdown
If you get past the error show above, then you will get a loader error on the md file when you try to import it. 
All that worked fine in Quasar Webpack V3, but it's not working in V4+

**Comment by sonicviz** [comment]
@hawkeye64 Any chance of getting the fix for this, as outlined in this thread, implemented asap?
https://github.com/quasarframework/quasar-ui-qmarkdown/issues/407 

ty.
