### ISSUE TITLE
Is there an updated tutorial? The old version seems outdated and not working. 

### ISSUE THREAD

**Issue by 0pen5un** [quasarframework/quasar-ui-qmarkdown#403]
Hello,
I recently tried to use qmarkdown by following the old tutorial [https://qmarkdown.netlify.app/all-about-qmarkdown/installation-types], but I encountered issues, and the component did not work as expected. Below are the details about my environment and the steps I followed:

**quasar info**
- Operating System - Windows_NT(10.0.22631) - win32/x64
- NodeJs - 22.11.0
- bun - 1.1.36
- @quasar/cli - 2.4.1
-  quasar - 2.17.4
- @quasar/app-vite - 2.0.0-rc.3
- vite - 6.0.0-beta.10
- @quasar/quasar-app-extension-qmarkdown - 2.0.0-beta.10

![图片](https://github.com/user-attachments/assets/ecfa3780-fdf7-4ed2-9f4b-6afa2783d23a)
![图片](https://github.com/user-attachments/assets/298a115d-9719-4716-a754-6e7fc678a72a)

**Comment by 2897924003** [comment]
I think it's a good idea to use q-markdown as conveniently as q-editor.

**Comment by 0pen5un** [comment]
I think it's a good idea to use q-markdown as conveniently as q-editor.
