### ISSUE TITLE
Some emojis are not shown correctly

### ISSUE THREAD

**Issue by heartbeatLV** [quasarframework/quasar-ui-qmarkdown#41]
Browser: Firefox Developer 71.0b9 (64 bit)

In the markdown-it-emoji list the number icons are displayed, while in qmarkdown no.

[MarkdownIt Example](https://markdown-it.github.io/)
![immagine](https://user-images.githubusercontent.com/33943143/68866430-b49a0100-06f4-11ea-8e07-c7a0bdcf1a70.png)

**QMarkdown Screenshot**
![immagine](https://user-images.githubusercontent.com/33943143/68866258-6b49b180-06f4-11ea-8924-5df86348698a.png)

**Comment by hawkeye64** [comment]
Thanks for bring this up. I'll look into it.:heart:

**Comment by hawkeye64** [comment]
@heartbeatLV I don't know how you arrived at those numbers. What did you put in for the markdown? This image is from the Interactive Editor from the QMarkdown live site.
![image](https://user-images.githubusercontent.com/10262924/69762052-59213780-1126-11ea-9ffe-82792d613f80.png)

**Comment by heartbeatLV** [comment]
I wrote `:one: :two: :three: :four:` Here are some examples of browsers:

### Chrome 78.0.3904.108 (64 bit)
![immagine](https://user-images.githubusercontent.com/33943143/69791704-5d506200-11c5-11ea-8156-ef628107d98c.png)

### Firefox Developer 71.0b12 (64 bit)
![immagine](https://user-images.githubusercontent.com/33943143/69791865-a86a7500-11c5-11ea-8d3a-80cc88c8f452.png)

### Firefox 70.0 (64 bit)
![immagine](https://user-images.githubusercontent.com/33943143/69792248-8de4cb80-11c6-11ea-8560-39565cf1a922.jpeg)

**Comment by hawkeye64** [comment]
This is what I get for Firefox 70.0.1 (64-bit)
![image](https://user-images.githubusercontent.com/10262924/69806413-04220780-11a0-11ea-85d0-1ab4c0e87d4c.png)
It's interesting that different browser show different emoticons. I will investigate why there is a difference.

**Comment by hawkeye64** [comment]
Ok, so found out that emojies are unicode chars and that the system and/browser is responsible for the display of them. They are universally accepted, so a heart :heart: still shows as a heart, etc. But, what gets displayed is what's installed on the system. The various flavors of Linux means there will be different emojie set installed; which is the same for browsers. FF uses a different emojie set than Chrome. Nothing can be done about this.

Closing this issue
