### ISSUE TITLE
Quasar-ui-gmarkdown installation issue

### ISSUE THREAD

**Issue by ghaddon** [quasarframework/quasar-ui-qmarkdown#48]
**Describe the bug**
Upon installation of  quasar-ui-qmarkdown with "quasar ext add qmarkdown" on the command line I get the following error.

C:\Users\ghadd\VSProjectsQuasar\firsttests>quasar ext add qmarkdown
 app:extension Installing "qmarkdown" Quasar App Extension +0ms

 app:extension Retrieving "quasar-app-extension-qmarkdown"... +2ms
 app:spawn [sync] Running "npm install --save-dev quasar-app-extension-qmarkdown" +1ms

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/quasar-app-extension-qmarkdown - Not found
npm ERR! 404 
npm ERR! 404  'quasar-app-extension-qmarkdown@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ghadd\AppData\Roaming\npm-cache\_logs\2019-11-26T19_05_42_424Z-debug.log

 app:spawn ⚠️  Command "npm" failed with exit code: 1 +3ms
 app:extension ⚠️  Failed to install quasar-app-extension-qmarkdown +1ms

**To Reproduce**
just run "quasar ext add "qmarkdown" from terminal command.

**Expected behavior**
I expect the quasar ext qmarkdown to be installed.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 build 1909
- @quasar/cli@1.0.3

**Additional context**
nothing

**Comment by hawkeye64** [comment]
Try this one:
```shell
quasar ext add @quasar/qmarkdown
```
You were installing an old, old one that was not under @quasar domain

**Comment by ghaddon** [comment]
Jeff,
Thanks, worked.
Gary
    On Tuesday, November 26, 2019, 01:55:47 PM MST, Jeff Galbraith <notifications@github.com> wrote:  
 
 
Try this one:
quasar ext add @quasar/qmarkdown
You were installing an old, old one that was not under @quasar domain
