### ISSUE TITLE
quasar-ui-qmarkdown error when running quasar dev

### ISSUE THREAD

**Issue by ghaddon** [quasarframework/quasar-ui-qmarkdown#49]
**Describe the bug**
After successfully run the installation of quasar-ui-qmarkdown I receive the following error:

These dependencies were not found:

* src/markdown/configurator-help-general.vmd in ./node_modules/babel-loader/lib??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/base-configurator-toolbar.vue?vue&type=script&lang=js&
* src/markdown/configurator-overview-general.vmd in ./node_modules/babel-loader/lib??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/base-configurator-toolbar.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save src/markdown/configurator-help-general.vmd src/markdown/configurator-overview-general.vmd

**To Reproduce**
1.Install @quasar/quasar-app-extension-qmarkdown": "^1.0.3"
2. run quasar dev

**Expected behavior**
Work as before.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows build 1909
 - @quasar/cli@1.0.3
 - @quasar/app": "^1.3.0"

**Additional context**

**The use of VMD files has been working. Things started to change when moving to @quasar/quasar-app-extension-qmarkdown": "^1.0.3".**

Following install instructions at https://quasarframework.github.io/quasar-ui-qmarkdown/docs
for VMD extension files.

**Comment by hawkeye64** [comment]
Fixed in v1.0.4 - sorry for the inconvenience

**Comment by ghaddon** [comment]
Jeff,
Thanks for your quick turnaround on the problem.Really like what you have done. with this extension.
Gary

    On Tuesday, November 26, 2019, 03:03:53 PM MST, Jeff Galbraith <notifications@github.com> wrote:  
 
 
Fixed in v1.0.4 - sorry for the inconvenience

**Comment by ghaddon** [comment]
Jeff,
I'm getting a different error now.I'm happy to go back through GitHub but thought I would just send you a heads-up.

It may be a finger check.  I think it may be looking for the raw-loader library.
Module build failed (from ./node_modules/ware-loader/lib/index.js):ReferenceError: renderMarkdown is not defined
Gary

    On Tuesday, November 26, 2019, 03:03:53 PM MST, Jeff Galbraith <notifications@github.com> wrote:  
 
 
Fixed in v1.0.4 - sorry for the inconvenience
