### ISSUE TITLE
missing renderMarkdown function

### ISSUE THREAD

**Issue by ghaddon** [quasarframework/quasar-ui-qmarkdown#50]
**When running "quasar dev"  I receive the following error.**

 error  in ./src/markdown/configurator-help-general.vmd

Module build failed (from ./node_modules/ware-loader/lib/index.js):
  ReferenceError: renderMarkdown is not defined

  - index.js:73 Object.middleware
    [firsttests]/[@quasar]/quasar-app-extension-qmarkdown/src/index.js:73:26

  - index.js:53 
    [firsttests]/[ware-loader]/lib/index.js:53:19

  - Array.forEach

  - index.js:52 Object.module.exports
    [firsttests]/[ware-loader]/lib/index.js:52:16

**To Reproduce**
1. associate vmd extension markdown to file
2. run quasar dev 
3. See error

**Expected behavior**
Clean compile.

**Desktop (please complete the following information):**
 +-- OS: Windows 10 build 1909
 +-- @vue/cli@3.12.1
 +-- @vue/cli-service-global@3.12.1
 +-- @quasar/cli@1.0.3
 +-- @quasar/app": "^1.3.1"
 +-- @quasar/quasar-app-extension-qmarkdown": "^1.0.5",

**Additional context**

**Comment by hawkeye64** [comment]
@ghaddon Thanks for finding these. :heart: I apologize the transfer to the new UI kit has not been without issues. Should have this fixed shortly.

**Comment by hawkeye64** [comment]
Fix is in v1.0.6

**Comment by ghaddon** [comment]
Just applied and everything is working.

Thanks,
Gary

**Comment by hawkeye64** [comment]
Thanks for getting back to me and letting me know.
