### ISSUE TITLE
Use links for the page headers

### ISSUE THREAD

**Issue by heartbeatLV** [quasarframework/quasar-ui-qmarkdown#56]
**Example**
```
# heading
[link](#heading)
```

**Is your feature request related to a problem? Please describe.**
when you click on a link a new page is opened

**Describe the solution you'd like**
it should open the link on the page

**Comment by hawkeye64** [comment]
@heartbeatLV Thanks for the feedback. :heart: I'll see what I can do. Is this for imported .md files?

**Comment by heartbeatLV** [comment]
@hawkeye64 yes, but it also happens on the app-extension demo page

**Comment by hawkeye64** [comment]
This is added in v1.0.13

See: https://quasarframework.github.io/quasar-ui-qmarkdown/docs#Anchor-Links
