### ISSUE TITLE
Newlines must not be rendered

### ISSUE THREAD

**Issue by MehrCurry** [quasarframework/quasar-ui-qmarkdown#73]
**Describe the bug**
If there is a newline in the markdown text you will get a line break in the resulting html.

**To Reproduce**
```
import text from '../markdown/howto.md'

<q-markdown :src="howto" />
```
where the file contains plain text with newlines.

**Expected behavior**
Newlines should be ignored.

**Desktop (please complete the following information):**
 - OS: MacOS, Linux
 - Browser: firefox, chrome, ...

**Comment by hawkeye64** [comment]
@MehrCurry Unless I am mistaking what you mean, this is conventional markdown.
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#lines

Basically:
1 line break = <br>
2 line breaks the paragraph above = <p>...</p>

**Comment by MehrCurry** [comment]
I have setup a demo project where you can see what is wrong from my point of view.

https://github.com/MehrCurry/newline-demo

The same text is in the README.md (so rendered by github) and in the app.

Github
<img width="162" alt="grafik" src="https://user-images.githubusercontent.com/328753/74502740-c99e5000-4eee-11ea-995a-ac2e839f1544.png">

QMarkdown
<img width="188" alt="grafik" src="https://user-images.githubusercontent.com/328753/74502777-e5095b00-4eee-11ea-9f80-98a43ec8ee19.png">

**Comment by hawkeye64** [comment]
@MehrCurry 
![image](https://user-images.githubusercontent.com/10262924/74536723-e25e3400-4ef5-11ea-86c7-f7b529556926.png)
https://quasarframework.github.io/quasar-ui-qmarkdown/demo

I suspect that the width (style) of your parent is not correct.
