### ISSUE TITLE
when the line numbers of code less than 3, the size of pre tag is to big

### ISSUE THREAD

**Issue by sgkind** [quasarframework/quasar-ui-qmarkdown#74]
**Describe the bug**
when the line numbers of code less than 3, the size of pre tag is to big

**To Reproduce**
1. go to https://quasarframework.github.io/quasar-ui-qmarkdown/demo
2. in the Interactive Editor
3. input
```
$ sudo apt update
$ sudo apt upgrade
```

**Expected behavior**
the size of pre should be equal the size of code

**Screenshots**
![截图_2020-02-08_13-48-22](https://user-images.githubusercontent.com/17806687/74079987-c253ee00-4a79-11ea-9efa-30b6782fd8f7.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Browser [e.g. chrome, safari] chrome & firefox

**Comment by hawkeye64** [comment]
@sgkind The Interactive Editor is using class `fit' for the parent, which is going to cause the child to fit the parent. If you open dev tools, edit the `q-markdown fit bordered q-pa-sm` and remove `fit` you will see what happens. This has nothing to do with QMarkdown.

**Comment by hawkeye64** [comment]
Nope, sorry. This is a valid bug.

**Comment by hawkeye64** [comment]
![image](https://user-images.githubusercontent.com/10262924/74092664-6c387800-4a84-11ea-9779-3b25c259c5ce.png)

Fix will be in v1.0.23
