### ISSUE TITLE
QSplitter : same height on both panels

### ISSUE THREAD

**Issue by Fulbert** [quasarframework/quasar-ui-qmarkdown#77]
**Is your feature request related to a problem? Please describe.**
I'd like to have a textarea on one side, and a QMarkdown on the other side. I want my textarea to fit the panel. I see no easy way to do so, because the markdown panel height doesn't follow the preview panel height.

**Describe the solution you'd like**
Either add `after-style` and `before-style` so we can alter height or make sure both panel have same height.

**Describe alternatives you've considered**
See above.

**Additional context**
![image](https://user-images.githubusercontent.com/4991264/77442989-0f521080-6deb-11ea-9dee-3a7a14961912.png)

Thanks.

**Comment by Fulbert** [comment]
Hi,

Why would it be reported on QMarkdown? This component works fine. I think this is more related to QSplitter ?

**Comment by hawkeye64** [comment]
Does this work if you add `class="fit"` ??

**Comment by hawkeye64** [comment]
@Fulbert create a codepen and we will get this figured out

**Comment by Fulbert** [comment]
No it doesn't : https://codepen.io/gregoirelannoy/pen/GRJwoZe?editable=true&editors=101

**Comment by hawkeye64** [comment]
@Fulbert You have to give the QSplitter a height in order for the `fit` class to work - it's a css issue
https://codepen.io/Hawkeye64/pen/abOPymW?editors=1010
