### ISSUE TITLE
Markdown WYSIWYG Editor?

### ISSUE THREAD

**Issue by rfox12** [quasarframework/quasar-ui-qmarkdown#78]
Absolutely amazing Quasar extension--I hope to use it.  Do you have a suggestion on how to provide an WYSIWYG markdown editor for your users?  Something similar to Quasar's core WYSIWYG editor but generates markdown instead of HTML on the back end?  Thanks for your time and contributions.

**Comment by hawkeye64** [comment]
@rfox12 No, this has been on my radar for a long time, but I just haven't had time to implement it. Hopefully, some time in the future, but it won't be any time soon.
