### ISSUE TITLE
White space (empty lines) got removed

### ISSUE THREAD

**Issue by alexeigs** [quasarframework/quasar-ui-qmarkdown#84]
With the last update (I guess) empty lines between paragraphs now get removed. Was that intended? How would you recommend keeping some spacing between paragraphs?

**Comment by hawkeye64** [comment]
@alexeigs Thanks for bringing this up. I'll investigate. It's likely an upstream change.

**Comment by hawkeye64** [comment]
@alexeigs I have done some extensive testing and this is what I found.

The current release does not have the issue that you have described

![image](https://user-images.githubusercontent.com/10262924/81172160-f6488d80-8f5a-11ea-8775-0e1ebee1c5f2.png)

This is the Interactive Editor for the current version.
That being said, when I tried the UMD examples on Codepen, this issue does exhibit. 

So, here's the thing about markdown, so it will be parsed properly:
It should always be left-aligned on the 0-th column in your editor
Codepen is always adjusting the indentation now, so I can't make markdown left-justified, which is probably causing this issue.
I went back to 1.10.0 for testing and still same issue on Codepen (only).

Can you tell me how you are using QMarkdown?
