### ISSUE TITLE
How to get "\n" to render a new line. 

### ISSUE THREAD

**Issue by gillisig** [quasarframework/quasar-ui-qmarkdown#85]
In your docs you have this as an example

```<q-markdown src=":::\nThis is a **test** of markdown\n:::"></q-markdown>```

But when I try to use \n in my app it just renders \n as text. 

Also if I take the example from the docs and paste it into the demo tool, the same issue happens.

![image](https://user-images.githubusercontent.com/5390864/82093061-e9116880-96e9-11ea-9dfc-54e1b5c793a3.png)

So how do I get it to work?

**Comment by hawkeye64** [comment]
This is not how the slot should work (the demo in image), but should be possible when using the `src` property (as in code example you have above).

How exactly are you using it?

**Comment by gillisig** [comment]
Hi @hawkeye64 and thanks for the quick response.

I have a data string with some markdown in it, it looks like this ```"\n## v1.1.0\n\nNew: Pro version\nNew: Dark mode for Pro version\n\n## v1.0.1\n\bug fixes and minor updates\n"``` that I'm then passing to the q-markdown component. 

I tried using both src and passing it with curly brackets, showed the same results.

As a matter of fact if I just copy the example from the docs and use that in my project it doesn't work either. Heres screenshots of the code and the results:

![image](https://user-images.githubusercontent.com/5390864/82096814-3513db80-96f1-11ea-8c06-7479c2f821d4.png)

![image](https://user-images.githubusercontent.com/5390864/82096855-45c45180-96f1-11ea-9189-49cd83ac6160.png)

**Comment by gillisig** [comment]
I figured it out, you actually need to use ":src=" instead of just "src", even when not passing data.

So the code from the docs would have to be ```<q-markdown :src="':::\nThis is a **test** of markdown\n:::'"></q-markdown>```

Thanks again @hawkeye64 for the quick reply though. Have a nice weekend!

**Comment by hawkeye64** [comment]
@gillisig This is fixed in v1.0.25
You should not need to jump through hoops now. There is a regex replace to convert `\\n` to `\n`

**Comment by gillisig** [comment]
@hawkeye64 awesome, nice work!
