### ISSUE TITLE
Prop to disable blockquotes

### ISSUE THREAD

**Issue by mickey58github** [quasarframework/quasar-ui-qmarkdown#87]
Hi Jeff,
I'm a very happy user of QMarkdown with my Quasar project. 

I would need a property to **disable blockquotes** (which use "> .. <", ">> ... <<", etc.), since I need to use these "<" and ">" symbols for mathematical comparisons in the markdown text. 

Or is there some kind of escaping available, to use them in the markdown without creating blockquotes?

Thanks a lot, Michael

**Comment by hawkeye64** [comment]
@mickey58github Have you tried escaping? `\<` or `\>`

**Comment by mickey58github** [comment]
@hawkeye64 - thanks, the escaping works. I was not aware that \ can be used as an escape character. 

Nevertheless, disabling the blockquotes would be my preferred solution, since my users put formulas into the markdown that often use the comparison operators, while block quotes will be rarely used. Since you have properties to disable almost all markdown tags, I wonder why you don't have it for blockquotes? Is there a specific reason?

**Comment by hawkeye64** [comment]
Fixed in v1.0.26

**Comment by mickey58github** [comment]
@hawkeye64 - thanks a lot, will try it out asap

**Comment by mickey58github** [comment]
@hawkeye64 - upgraded from V1.0.23 to .26 and tested it - works very well. Thanks for your quick response.
